# XGBoost - Wine Quality (Regression) - for Inference

[UCI - Wine Quality Data Set](https://archive.ics.uci.edu/ml/datasets/wine+quality)

In [2]:
!pip install xgboost

Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com


In [4]:
import numpy as np
import pandas as pd
import time

### Load Dataset

In [5]:
df = pd.read_csv('./data/wine_concat.csv')

y = df['quality']
X = df.drop(['quality'], axis=1)

X = pd.get_dummies(X)  
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.66         0.00             1.8      0.075   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 13.0                  40.0   0.9978  3.51       0.56   

   alcohol  color_red  color_white  
0      9.4          1            0  
1      9.8          1            0  
2      9.8          1            0  
3      9.8          1            0  
4      9.4          1            0

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2) # Split train/test dataset

### Load Model and Predict

In [11]:
from xgboost import XGBRegressor
model = XGBRegressor()

model_name = "./output/xgboost_wine_quality.json"

model.load_model(model_name)

In [12]:
model.predict(X_test)

array([6.4810886, 4.7421913, 5.1624813, ..., 5.9254093, 5.273866 ,
       6.331496 ], dtype=float32)

### Test dataset

In [65]:
X_test[:1]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
3487            6.6              0.24         0.28             1.8      0.028   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
3487                 39.0                 132.0  0.99182  3.34       0.46   

      alcohol  color_red  color_white  
3487     11.4          0            1

In [66]:
model.predict(X_test[:1])

array([6.4810886], dtype=float32)

### Translate to Json

In [67]:
sample = X_test[:1]

In [69]:
sample.to_json()

'{"fixed acidity":{"3487":6.6},"volatile acidity":{"3487":0.24},"citric acid":{"3487":0.28},"residual sugar":{"3487":1.8},"chlorides":{"3487":0.028},"free sulfur dioxide":{"3487":39.0},"total sulfur dioxide":{"3487":132.0},"density":{"3487":0.99182},"pH":{"3487":3.34},"sulphates":{"3487":0.46},"alcohol":{"3487":11.4},"color_red":{"3487":0},"color_white":{"3487":1}}'

In [49]:
sample.to_json(orient='index')

'{"3487":{"fixed acidity":6.6,"volatile acidity":0.24,"citric acid":0.28,"residual sugar":1.8,"chlorides":0.028,"free sulfur dioxide":39.0,"total sulfur dioxide":132.0,"density":0.99182,"pH":3.34,"sulphates":0.46,"alcohol":11.4,"color_red":0,"color_white":1}}'

In [83]:
sample.to_json(orient='records')

'[{"fixed acidity":6.6,"volatile acidity":0.24,"citric acid":0.28,"residual sugar":1.8,"chlorides":0.028,"free sulfur dioxide":39.0,"total sulfur dioxide":132.0,"density":0.99182,"pH":3.34,"sulphates":0.46,"alcohol":11.4,"color_red":0,"color_white":1}]'

### Create json file

In [107]:
 X_test[:2]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
3487            6.6              0.24         0.28             1.8      0.028   
1162            8.7              0.78         0.51             1.7      0.415   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
3487                 39.0                 132.0  0.99182  3.34       0.46   
1162                 12.0                  66.0  0.99623  3.00       1.17   

      alcohol  color_red  color_white  
3487     11.4          0            1  
1162      9.2          1            0

In [108]:
X_test[:2].to_json('samples.json',orient='records')

### Load json file

In [104]:
records = pd.read_json('samples.json')
data = pd.DataFrame(records)
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            6.6              0.24         0.28             1.8      0.028   
1            8.7              0.78         0.51             1.7      0.415   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                   39                   132  0.99182  3.34       0.46   
1                   12                    66  0.99623  3.00       1.17   

   alcohol  color_red  color_white  
0     11.4          0            1  
1      9.2          1            0

### Inference

In [105]:
model.predict(data)

array([6.4810886, 4.7421913], dtype=float32)